update squisher

diff --git a/releasetools/squisher b/releasetools/squisher
--- a/releasetools/squisher
+++ b/releasetools/squisher
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Squish a otapackage for distribution
+# Squish a CM otapackage for distribution
 # cyanogen
 #
 
@@ -39,6 +39,35 @@ OPTICHARGER=$ANDROID_BUILD_TOP/device/motorola/spyder/releasetools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
+
+# Some products want a squashfs for xbin for space
+case "$TARGET_PRODUCT" in
+	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+	*) WANT_SQUASHFS=0 ;;
+esac
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+	fatal=0
+	MKSQUASHFS_VER_REQ=4
+	if type mksquashfs >/dev/null 2>&1; then
+		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+			echo
+			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+			fatal=1
+		fi
+	else
+		echo
+		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+		fatal=1
+	fi
+
+	if [ "$fatal" -ne 0 ]; then
+		echo
+		echo "       Unoptimized package is still available at"
+		echo "         $OTAPACKAGE"
+		exit $fatal
+	fi
+fi
 
 REPACK=$OUT/repack.d
 printf "Sanitizing environment..."
@@ -126,7 +155,14 @@ cp -f $ANDROID_BUILD_TOP/device/motorola/spyder/prebuilt/lib/libvoicesearch.so $
 # Determine what to name the new signed package
 REALDATE=`date +%m-%d`
 
-OUTFILE=$OUT/RAZR-6_14_84-CM9-$REALDATE-UNOFFICIAL.zip
+if [ -z "$CYANOGEN_NIGHTLY" ]; then
+	MODVERSION=`sed -n -e'/ro\.cm\.version/s/^.*=//p' $REPACK/ota/system/build.prop`
+	: ${MODVERSION:=nightly}
+    OUTFILE=$OUT/RAZR-6_14_84-CM9-$REALDATE-UNOFFICIAL.zip
+	echo MODVERSION: $MODVERSION
+else
+	OUTFILE=$OUT/update-squished.zip
+fi
 
 # Pack it up and sign
 printf "Zipping package..."
